### PR TITLE
Add endpoint to unsubscribe a user on AK

### PR DESCRIPTION
**Pull request by Tuuleh**

### CODE REVIEW

**Comment by rodrei** [comment]
@Tuuleh specs are not passing, could you please fix them so we can merge this? Also, can you please also rebase master? Thanks!

**Comment by rodrei** [comment]
Re: code review. The comment I have is the same one as before, I'd extract the DynamoDB details into a separate service.

**Comment by Tuuleh** [comment]
Hm, the specs that are failing are unrelated to these (they're for showing members), but yea, we'll need to look at those. I suggest we do the DynamoDB refactoring on its own branch.

**Comment by rodrei** [comment]
@Tuuleh The specs are passing on master/development, so the issue is on this branch. I see a few fixtures are deleted here, maybe it's related to that?

**Comment by Tuuleh** [comment]
yea, I had to delete a ton of fixtures because someone had had the AK url wrong when recording fixtures (if you have a trailing slash, they send back a 301 and then take you to the right page). It's been fixed on this branch - I'll rebase and see about fixing these, too.

**Pull request merged**
